global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'
rule_files:
 #   - "/var/app/prometheus/alert.rules"

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/prometheus'
    static_configs:
      - targets: 
        - 'spring:8081'
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'